# Universidad de San Carlos de Guatemala
# Facultad de Ingeniería
# Escuela de Estudios de Postgrado
# Curso: Mineria de Datos.
# Introducción a la Minería de Datos
# Por: Denys Fernando Orozco Escobar
---
title: "RANDOM FOREST"
output: html_notebook
---

```{r}
### Paso numero 1: importacion de librerias
library(randomForest)
library(dplyr)
```

```{r}
### Paso numero 2: carga de archivos
migracion <- read.csv("MIGRACION_BDP.csv", sep = ",")
```

```{r}
### Paso numero 3: omitir datos asignados con na
migracion <- na.omit(migracion)
```

```{r}
### Factorizando el departamento en busqueda de poder agrupar o categorizar por departamento
migracion$DEPARTAMENTO <- as.factor(migracion$DEPARTAMENTO)
### migracion <- migracion[-3]
migracion <- migracion[,c(-2,-3,-4,-6,-7,-8)]
```

```{r}
### Generando una muestra 100 elementos
set.seed(100)
migracion <- migracion[sample(1:nrow(migracion)),]
indice <- sample(1:nrow(migracion), 0.8*nrow(migracion))

```
```{r}
### Entrenando el algoritmo
entrenamiento <- migracion[indice,]
prueba <- migracion[-indice,]
```

```{r}
### Generando el RANDOM FOREST
bosque1 <- randomForest(DEPARTAMENTO ~ PEI3 + PEI4 + PEI5, data = entrenamiento, ntree = 50, mtry = 3)

### Prediccion
entreno <- predict(bosque1, prueba)

### Convertir set de datos en frame
data_frame_de_bosque1 <- data.frame(
        PEI3 = 1,
        PEI4 = 25,
        PEI5 = 2018
)

### PREDICCION DEL DATAFRAME ANTERIOR
prediccion <- predict(bosque1, data_frame_de_bosque1)
prediccion
```

```{r}
### Generando el RANDOM FOREST
bosque2 <- randomForest(AREA ~ PEI3 + PEI4 + PEI5, data = entrenamiento, ntree = 75, mtry = 3)

### Prediccion
entreno <- predict(bosque2, prueba)

### Convertir set de datos en frame
data_frame_de_bosque2 <- data.frame(
        PEI3 = 1,
        PEI4 = 25,
        PEI5 = 2018
)

### PREDICCION DEL DATAFRAME ANTERIOR
prediccion <- predict(bosque2, data_frame_de_bosque2)
prediccion
```

```{r}
### Generando el RANDOM FOREST
bosque3 <- randomForest(PEI4 ~ AREA + PEI3 + PEI5, data = entrenamiento, ntree = 50, mtry = 3)

### Prediccion
entreno <- predict(bosque3, prueba)

### Convertir set de datos en frame
data_frame_de_bosque3 <- data.frame(
        AREA = 1,
        PEI3 = 1,
        PEI5 = 2015
)

### PREDICCION DEL DATAFRAME ANTERIOR
prediccion <- predict(bosque3, data_frame_de_bosque3)
prediccion
```

```{r}

```

